version: '3.4'

services:
  catalogdb:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalogs/Catalog.Api/Dockerfile
volumes:
  mongo_data: